### ISSUE TITLE
generate_relation: Connection adapter not supported: litedb (Groupdate::Error)

### ISSUE THREAD

**Issue by adrienpoly** [oldmoe/litestack#13]
I am trying to use the groupdate gem to group time series by dates

When I use the `liltedb` adapter add call a query like that 
```ruby
Ahoy::Visit.group_by_day(:started_at).count
```

I am getting this error

```bash
gems/3.2.0/gems/groupdate-6.2.1/lib/groupdate/magic.rb:208:in `generate_relation': Connection adapter not supported: litedb (Groupdate::Error)
```

The error is reported in groupedate code but I don't have the same error when I use the sqlite3 adapter

**Comment by oldmoe** [comment]
The groupdate gem is explicitly looking for the sqlite3 adapter, I will try to include litedb support for groupdate in a new release

**Comment by oldmoe** [comment]
I would like to get your (and whoever is reading this) thoughts on the different options we have here:

- Provide a compatibility mode for Litestack that basically extends the current sqlite3 adapter 
- Provide an adapter specifically for the groupupdate gem (just inherit from their existing sqlite3 implemention) 

The first option has the advantage of allowing all gems that rely on the existence of the sqlite3 adapter to work seamlessly, though it could limit my future (hopefully not far off) plan to introduce a new sqlite3 driver instead of the defacto one.

The second option solves the problem for group update but it will add gem specific code (not a huge issue) and will need more code in place to support other gems with similar functionality.

**Comment by kriansa** [comment]
I would definitely go for the first option. It will not only make it compatible with `groupupdate` but also with any gem that expects a specific adapter named `SQLite` for compatibility purposes.

If your planned new sqlite3 driver is to be interface-compatible with the existing one, then I don't see an immediate issue, _theoretically_.

**Comment by oldmoe** [comment]
I think that makes sense, I will think of a good way to introduce that comparability mode and see when I can get started on it

**Comment by oldmoe** [comment]
I believe there is a pretty straight forward way around this by registering litedb as an adapter for groupdate as described here https://github.com/ankane/groupdate/pull/277
