### ISSUE TITLE
Error raised when calling Rails.cache.clear 

### ISSUE THREAD

**Issue by adrienpoly** [oldmoe/litestack#28]
When I try to call `Rails.cache.clear` I have this error message

```
...active_support/cache/litecache.rb:51:in `clear': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

I think the signature of method should be 

```diff
-def clear()
+def clear(options = nil)
  @cache.clear
end
```

**Comment by nshki** [comment]
Hi there! Wanted to comment on this older issue since it still seems to occur with v0.4.2. I checked the `master` branch of this project and saw that the change in #29 doesn't seem to be present in the `litecache.rb` file [here](https://github.com/oldmoe/litestack/blob/master/lib/active_support/cache/litecache.rb#L49).
