### ISSUE TITLE
Active Storage service?

### ISSUE THREAD

**Issue by ariel-codes** [oldmoe/litestack#8]
Hey, love the rationale behind the gem! I'm trying it out for some hobby projects and liking it so far.
And something I've always wondered is: why not use SQLite for blob storage? [Raw performance looks pretty good](https://www.sqlite.org/fasterthanfs.html)

Is this on the roadmap? I'd love to help

**Comment by oldmoe** [comment]
Thanks a lot for the praise!, at the moment I am trying to make sure this is hardened enough for production use. 

Now looking at active storage, I have considered it, but haven't yet done any benchmarking to understand the potential limitations, specially with large file sizes. The current state of Ruby sqlite3 drivers are not well suited for that because of the extra memory copying they required during parameter binding.

That said, there is potential here for a very interesting implementation that seamlessly supports file streaming using the sqlite3 incremental blob IO interface, combined with Rack 3 compliant servers.

I will do some testing to check the potential insert/update limitations and report progress here.

**Comment by oldmoe** [comment]
Took me ages to get to this, but my testing showed the filesystem to run circles around SQLite when inserting larger files, as we get to 10s and 100s of megabytes the filesystem (ZFS in my case) becomes order(s) of magnitude faster. I can see an opportunity for SQLite acting as a metadata store, but so far, if you are running everything on a single machine, then I would think the ActiveStorage filesystem driver fits the bill.
